name: windows-x64

on:
  push:
    branches:
      - master

jobs:
  windows_x64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        # python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install sherpa-onnx
        shell: bash
        run: |
          pip install --verbose https://huggingface.co/csukuangfj/sherpa-onnx-wheels/resolve/main/sherpa_onnx-1.3.2-cp38-cp38-win_amd64.whl

      - name: Run sherpa-onnx
        shell: bash
        run: |
          python3 -c "import sherpa_onnx; print(sherpa_onnx.__file__)"
          # ls -lh /c:/hostedtoolcache/windows/Python/3.8.10/x64
          # ls -lh /c:/hostedtoolcache/windows/Python/3.8.10/x64/bin

          # sherpa-onnx --help
          #
      - name: ls
        shell: cmd
        run: |
          dir C:\hostedtoolcache\windows\Python\3.8.10\x64\lib
          dir C:\hostedtoolcache\windows\Python\3.8.10\x64\bin
