name: test-docker

on:
  push:
    branches:
      - master
      - docker

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: ubuntu:16.04
            # options: -v ${{ github.workspace }}:/var/www
            run: |
              uname -a


