name: test-docker2

on:
  push:
    branches:
      - master
      - docker

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # see https://github.com/pytorch/test-infra/blob/9e3d392690719fac85bad0c9b67f530e48375ca1/tools/scripts/generate_binary_build_matrix.py
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: pytorch/manylinux-cuda102
            options: -v ${{ github.workspace }}:/var/www
            run: |
              echo "pwd: $PWD"
              uname -a
              id
              cat /etc/*release
              gcc --version
              nvcc --version
              which nvcc
              which gcc
              ls -lh /usr/local
              python3 --version
              which python3

