name: test-docker

on:
  push:
    branches:
      - master
      # - docker

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # see https://github.com/pytorch/test-infra/blob/9e3d392690719fac85bad0c9b67f530e48375ca1/tools/scripts/generate_binary_build_matrix.py
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: pytorch/manylinux-builder:cuda10.2
            options: -v ${{ github.workspace }}:/var/www
            run: |
              echo "pwd: $PWD"
              uname -a
              id
              cat /etc/*release
              gcc --version
              nvcc --version
              which nvcc
              which gcc
              ls -lh /usr/local
              python3 --version
              which python3

              yum -y install openssl-devel bzip2-devel libffi-devel xz-devel wget

              wget -qq https://www.python.org/ftp/python/3.8.16/Python-3.8.16.tgz
              tar xf Python-3.8.16.tgz
              cd Python-3.8.*
              ./configure --enable-optimizations --enable-shared --prefix=$PWD/py38
              make install

              ls -lh $PWD/py38
              ls -lh $PWD/py38/lib
              ls -lh $PWD/py38/bin

              export PATH=$PWD/py38/bin:$PATH
              export LD_LIBRARY_PATH=$PWD/py38/lib:$LD_LIBRARY_PATH

              python3 --version
              cd ../

              git clone --depth 1 https://github.com/k2-fsa/k2
              cd k2
              python3 -m pip install -U pip
              python3 -m pip install torch==1.10.0 cmake
              python3 -m pip install --force-reinstall typing-extensions==4.5.0
              python3 -m pip install wheel twine typing_extensions
              python3 -m pip install bs4 requests tqdm

              export CMAKE_CUDA_COMPILER_LAUNCHER=
              export K2_CMAKE_ARGS=" -DPYTHON_EXECUTABLE=/Python-3.8.16/py38/bin/python3 "
              export K2_MAKE_ARGS=" -j1 "

              python3 setup.py bdist_wheel
              cp ./dist/*.whl /var/www

              pushd /usr/local/cuda/lib64
              ln -s /usr/local/cuda/targets/x86_64-linux/lib/stubs/libcuda.so libcuda.so.1
              popd
              auditwheel repair --plat manylinux_2_17_x86_64 -w ./var/www ./dist/*.whl

      - name: Display
        shell: bash
        run: |
          ls -lh

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./*.whl
