name: test-docker

on:
  push:
    branches:
      - master
      - docker

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: pytorch/manylinux-builder:cuda10.2
            options: -v ${{ github.workspace }}:/var/www
            run: |
              uname -a
              id
              set -e
              gcc --version
              nvcc --version
              python3 -version


      # - name: Display
      #   shell: bash
      #   run: |
      #     ls -lh
      #
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: wheels
      #     path: ./*.whl
